@BASE_URL = http://127.0.0.1:5000


### Home
GET {{BASE_URL}}/
Content-Type: application/json


### Get All Books
GET {{BASE_URL}}/books
Content-Type: application/json


### Get Single Book by ID
GET {{BASE_URL}}/books/1
Content-Type: application/json


### Add Book
POST {{BASE_URL}}/books
Content-Type: application/json

{
  "title": "Node.js Architecture",
  "author": "Eng. Honest"
}


### Update Book
PUT {{BASE_URL}}/books/1
Content-Type: application/json

{
  "title": "Hablaheenna - Updated Edition"
}


### Delete Book
DELETE {{BASE_URL}}/books/3
Content-Type: application/json
