@HOST = {{$dotenv HOST}}
@PORT = {{$dotenv PORT}}


### Home
GET http://{{HOST}}:{{PORT}}/
Content-Type: application/json


### Get All Books
GET http://{{HOST}}:{{PORT}}/books
Content-Type: application/json


### Get Single Book by ID
GET http://{{HOST}}:{{PORT}}/books/1
Content-Type: application/json


### Add Book
POST http://{{HOST}}:{{PORT}}/books
Content-Type: application/json

{
  "title": "Node.js Architecture",
  "author": "Eng. Honest"
}


### Update Book
PUT http://{{HOST}}:{{PORT}}/books/1
Content-Type: application/json

{
  "title": "Hablaheenna - Updated Edition"
}


### Delete Book
DELETE http://{{HOST}}:{{PORT}}/books/3
Content-Type: application/json
