
@HOST = {{$dotenv HOST}}
@PORT = {{$dotenv PORT}}
@BASE_URL = http://{{HOST}}:{{PORT}}
@BOOK_ID = replace-with-real-mongodb-id

# Routes
# /books/create
# /books/all
# /books/get/:id
# /books/update/:id
# /books/delete/:id


### Create New Book
POST {{BASE_URL}}/books/create
Content-Type: application/json  

{
  "title": "Node.js Architecture",
  "author": "Eng. Honest"
}


### Get All Books
GET {{BASE_URL}}/books/all
Content-Type: application/json


### Get Single Book by ID
GET {{BASE_URL}}/books/get/{{BOOK_ID}}
Content-Type: application/json 


### Update Book
PUT {{BASE_URL}}/books/update/{{BOOK_ID}}
Content-Type: application/json

{
  "publishedYear": 2026,
  "genre": "Technology",
  "pages": 350
}


### Delete Book
DELETE {{BASE_URL}}/books/delete/{{BOOK_ID}}
Content-Type: application/json
